name: Build MacOS Monterey

on:
  push:
    branches:
       - main
       - ci-macos
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build-macos:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Print system info
      run: |
           uname -m
           ls /usr/local
    - name: Install Rosetta2
    - name: Install dependencies
      run: |
           brew update
           brew install tree cmake extra-cmake-modules
    - name: Install QT 6
      run: |
           brew install qt@6
           arch -arm64 brew install qt@6 || echo "No such Arch ARM"
           ls -lah /usr/local/Cellar/qt* >> ~/ls-cellar.txt
           tree --charset ascii /usr/local/Cellar/qt/ >> ~/qt-tree.txt
           
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
           cmake -B ${{github.workspace}}/build \
                 -DQt6_DIR=$(brew --prefix qt6)/lib/cmake/Qt6 \
                 -DCMAKE_INSTALL_PREFIX=qbrainwave.app \
                 -DCMAKE_OSX_ARCHITECTURES="x86_64" \
                 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

    - name: Build
      # Build your program with the given configuration
      run: |
           echo "Github workspace=${{github.workspace}}"
           echo "PWD=${PWD}"
           cd ${{github.workspace}}/build
           make
    
    - name: Build Package
      run: |
           cd ${{github.workspace}}/build
           $(brew --prefix qt6)/bin/macdeployqt qbrainwave.app || echo "Macdeploy FAILED"
           tree --charset ascii .
           
    - name: Prepare Artifact
      run: |
           cd ${{github.workspace}}/build
           if [[ -x artifacts ]]; then 
           rmdir -Rf artifacts
           fi
           mkdir artifacts
           cp -Rv qbrainwave.app artifacts/qbrainwave.app
           cp ~/qt-tree.txt artifacts
           cp ~/ls-cellar.txt artifacts


    - name: Upload tuningTrainer-mac
      uses: actions/upload-artifact@v3.0.0
      with:
        name: qbrainwave-macos
        path: ${{github.workspace}}/build/artifacts
        
