name: Build Windows

on:
  push:
    branches:
       - main
       - 0000-fix-workflows
  pull_request:
    branches: [ main ]

env:
  #  Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  TIME: 0000

jobs:
  build-windows:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
         
    steps:
    - name: Setup Base MINGW env
      run: |
           mkdir D:\artifacts
           Write-Output  ":: $env:PATH ::"
           try {  curl --version } catch { Write-Output ":: curl not found ::" }
           try {  wget --version } catch { Write-Output ":: wget not found ::"}
           try {  unzip --version } catch { Write-Output ":: unzip not found ::"}
           try {  tar --version } catch { Write-Output ":: tar not found ::"}
           try {  pip --version } catch { Write-Output ":: pip not found ::"}
           try {  python --version } catch { Write-Output ":: python not found ::"}
           try {  cmake --version } catch { Write-Output ":: Cmake not found ::"}
           try {  7z i } catch { Write-Output ":: 7zip not found ::"}

    - name: Upload qbrainwave-win-${{ env.TIME }}.zip
      uses: actions/upload-artifact@v3.0.0
      with:
        name: qbrainwave-win-${{ env.TIME }}
        path: D:\artifacts\
