name: Build MacOS Monterey

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string  
  push:
    branches:
       - main
       - ci-macos
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build-macos:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
#      with:
#          limit-access-to-actor: true
#          if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
#       timeout-minutes: 60
      
    - name: Prepare environment
      run: |
           if [[ -x ~/artifacts ]]; then 
           rmdir -Rf ~/artifacts
           fi
           mkdir ~/artifacts
    
    - name: Fetch dependencies
      run: |
           mkdir download
           cd download
           wget -q https://freeshell.de/~arturwro/downloads/brew-monterey-universal.tar.gz
           tar -xzf brew-monterey-universal.tar.gz -C ~

    - name: Type brew directory contents
      run: |
           mkdir ~/diagnostics
           find $(brew --prefix) > ~/diagnostics/brewdirectory.txt
    
    - name: Upload tuningTrainer-mac
      uses: actions/upload-artifact@v3.0.0
      with:
        name: brewdiag
        path: ~/diagnostics/
    
    - name: Create links
      run: |    
           BREWOPT=$(brew --prefix)/opt
           sudo mv ${BREWOPT} ${BREWOPT}.bak
           sudo mkdir ${BREWOPT}
           sudo chown -R $(whoami) /usr/local/opt
           sudo chmod u+w /usr/local/opt
           cd ~/brew-monterey-universal
           for i in *;
           do
           ver=$(cd ${i}; ls)
           sudo ln -vs "${PWD}/${i}/${ver}" "${BREWOPT}/${i}"
           done
           
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
           echo $(brew --prefix qt@6)
           cmake -B ${{github.workspace}}/build \
                 -DCMAKE_INSTALL_PREFIX=qbrainwave.app \
                 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          
    - name: Build
      # Build your program with the given configuration
      run: |
           echo "Github workspace=${{github.workspace}}"
           echo "PWD=${PWD}"
           cd ${{github.workspace}}/build
           make

    - name: Build Package
      run: |
           cd ${{github.workspace}}/build
           macdeployqt qbrainwave.app || echo "Macdeploy FAILED"
           file qbrainwave/Contents/MacOS/qbrainwave || echo "No such file"
           
    - name: Prepare Artifact
      run: |
           cd ${{github.workspace}}/build
           cp -Rv qbrainwave.app ~/artifacts/qbrainwave.app


    - name: Upload tuningTrainer-mac
      uses: actions/upload-artifact@v3.0.0
      with:
        name: qbrainwave-macos-universal
        path: ~/artifacts
    
    - name: Revert brew
      if: ${{ failure() }}
      run: |
           BREWOPT=$(brew --prefix)/opt
           sudo mv ${BREWOPT}.bak ${BREWOPT}
           sudo chown -R $(whoami) /usr/local/opt
           sudo chmod u+w /usr/local/opt
            
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
      with:
          limit-access-to-actor: true
          #install-dependencies: false
#      timeout-minutes: 60        
        
